name: TagView-CI-MinGW
 
on: [push]


env:
  QT_VERSION: 6.8.3

jobs:
  build:
    name: "Build"
    runs-on: windows-latest

    steps:
      - name: Install ninja (windows)
        run: choco install ninja

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{env.QT_VERSION}}
          arch: win64_mingw

      - name: Checkout source code
        uses: actions/checkout@v4
 
      - name: Build
        run: |
          Write-Host "✅ 最后检查一次PATH："
          $env:PATH -split ';' | ForEach-Object { Write-Host "  $_" }
          
          cmake -S . -B build_dir -G "Ninja Multi-Config"
          cmake --build build_dir --config Release